# DO NOT TO
config-version: 5
# DO NOT TOUCH^^^^

# When someone closes the shop it shuts completely out they will have to run the command again!
Straight_Back: true

# when someone closes the shop it goes back to the Category area they can then close it from there.
Back_to_Start: false

# This makes the Command only work when the player is in Survival
Survival: false

# This is Used to Ban Commands in only the Worlds Below.
Worlds: ["bannedworld1", "bannedworld2"] # You can add as Many as needed

# This adds an Exit Button to Categories Section of Plugin (Recommended to Leave false)
Category_ExitButton: true
Items_ExitButton: true

# Turns off Messages like Thanks for Using On Close!
Thanks: false

#Turns on or off the Command Confirmation Window
command_confirm: true

# Turns on or off Multi Shop Support!
Multi-Shop: true

# Default Shop for when the Player Runs the /shop command with no Arguments!
Default-Shop: "Shop"
Titles:
  # adding these is simple just put exactly what you have in the shop.yml as the name and then title after it and then the name!
  Default: "§0【 SHOP 】" ## This is default for when you don't add the titles Below!
  shoptitle: "§0【 SHOP 】"
  


Types:
  Toggle: true #it is NOT recommended to change this! (Changing this means the Plugin wont work This will be Fixed in a few updates!)
  Input: true # true or false (adds Number input player has to type)
  Slider: false # true or false (adds slider Input Player has to Slide the Slider)
  Slider_Minimum: 1 # Must be a Number (Number for Normal Slider)
  Slider_Maximum: 128 # Must be a Number (Number for Maximum Amount they can Buy)
  StepSlider: false # true or false (adds step Slider)
  Slider_Numbers: ["1", "15", "30", "64", "128"] # You can add more Numbers if you follow the Same format!