#  ██████╗░░█████╗░███╗░░██╗██████╗░░█████╗░███╗░░░███╗  ███╗░░░███╗░█████╗░████████╗██████╗░
#  ██╔══██╗██╔══██╗████╗░██║██╔══██╗██╔══██╗████╗░████║  ████╗░████║██╔══██╗╚══██╔══╝██╔══██╗
#  ██████╔╝███████║██╔██╗██║██║░░██║██║░░██║██╔████╔██║  ██╔████╔██║██║░░██║░░░██║░░░██║░░██║
#  ██╔══██╗██╔══██║██║╚████║██║░░██║██║░░██║██║╚██╔╝██║  ██║╚██╔╝██║██║░░██║░░░██║░░░██║░░██║
#  ██║░░██║██║░░██║██║░╚███║██████╔╝╚█████╔╝██║░╚═╝░██║  ██║░╚═╝░██║╚█████╔╝░░░██║░░░██████╔╝
#  ╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝╚═════╝░░╚════╝░╚═╝░░░░░╚═╝  ╚═╝░░░░░╚═╝░╚════╝░░░░╚═╝░░░╚═════╝░
#set start-working to false, if you want to disable plugin.
start-working: true
#you can add more strings in Messages.
Messages: ["§l§aMessage 1", "§l§bMessage 2", "§l§cMessage 3", "§l§dMessage 4", "§l§3Message 5", "§l§eMessage 6"]
#every 20 tick = 1 second, 100 ticks = 5 second, do not set RepeatTimer lower than 100 ticks.
RepeatTime: 100