---
version: 1.1.93
language to use: you could use de, fr, en, ro, zhsimp or zhtrad. (zhtrad is for traditional
  chinese, zhsimp for simplified chinese) if the file does not exist, it will create
  a default en file!
language: en
debugging: false
...
