---
version: 2.3.8
motd:
  '# ticks': line delay when showing multi-line motd texts.
  ticks: 15
  '# auto-motd': Automatically shows motd when entering world
  auto-motd: true
features:
  max-players: false
  protect: true
  border: true
  pvp: true
  motd: false
  no-explode: false
  unbreakable: false
  bancmds: true
  banitem: true
  gamemode: false
  gm-save-inv: false
...
